name: Publish package to the Maven Central Repository and GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Verify Version from pom.xml
        run: |
            # Extract the version from pom.xml
            POM_VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
            
            # Get the release tag from the GitHub context
            RELEASE_TAG=${{ github.ref }}
            
            # Remove "refs/tags/" from the release tag
            RELEASE_TAG=${RELEASE_TAG/refs\/tags\//}
          
            # Remove the 'v' prefix from the release tag, if present
            RELEASE_TAG=${RELEASE_TAG#v}
            
            if [ "$POM_VERSION" == "$RELEASE_TAG" ]; then
              echo "Version in pom.xml matches the release tag: $RELEASE_TAG"
            else
              echo "Error: Version in pom.xml ($POM_VERSION) does not match the release tag ($RELEASE_TAG)"
              exit 1
            fi
      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode -Dmaven.test.skip deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}