name: Build & Test

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  build-maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
      - name: Set up JDK 1.8
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # 3.12.0
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build and Test
        run: mvn --batch-mode package